### ISSUE TITLE
Code Review: Simplify MoleculeController::getSimilarityMatches() method

### ISSUE THREAD

**Issue by lganzzzo** [MichelML/chempp#20]
Hello ,

You can simplify [MoleculeController::getSimilarityMatches](https://github.com/MichelML/chempp/blob/master/src/controller/MoleculeController.hpp#L104) method:

```cpp
ENDPOINT("GET", "molecules/similarity_search/{structure}/*", getSimilarityMatches,
         PATH(String, structure),
         QUERY(Int64, limit, "limit", "100"),           //<-- Optional with default value
         QUERY(Float64, threshold, "threshold", "0.5")) //<-- Optional with default value
{
  return createDtoResponse(Status::CODE_200, m_moleculeService.getSimilarityMatches(structure, limitInt, thresholdFloat));
}
```

oatpp will automatically do all the mapping and type validation for query params.
Thus the `ENDPOINT_INFO` block can be simplified too.

Regards,
Leonid

**Comment by MichelML** [comment]
Thanks Leonid, will make sure to apply the change.
